### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ecoterrorist** [BlockyBorzan/BlockyRanks#1]
First of all, congratulations on creating the first ever viable competition/successor for Autorank! One is sorely needed, what with AR's lack of development in 8 months, bad decisions in the development that did happen, and no support for the latest versions of Spigot and Paper 1.13.2.

Here are a few more things/plugins I believe BlockyRanks would benefit from tracking for rank requirements:
1. JobsReborn
  - Total job levels, experience
2. Votes (NuVotifier maybe?)
3. Any/all Skyblock plugins (ASkyblock, SkyBlockEarth, etc)
  - Island level
4. Player/Mob Kills

You could also create a basic stats plugin for BR to hook into, if that's something you're interested in.

I wonder if it would be possible to use PAPI placeholders as "rankup requirements", and have BlockyRanks consider the requirement completed when the placeholder is a certain value for the user.. That's probably impossible and doesn't make sense anyways.

**Comment by BlockyBorzan** [comment]
Thank you for the kind words - though I must admit I have not heard of Autoranks and did not make this plugin to replace anybody else's - it is nice to hear that I seem to have accomplished something special here. 

As for your feature request: I will add it to the [**list of future plans**](https://github.com/BlockyBorzan/BlockyRanks/wiki/Future-Plans) for BlockyRanks, even though what you suggested is basically already on there. The requirements will definitely expand and the goal is to offer as much customizability as possible.

I don't know if the stats plugin is something worth doing as there must surely be one out there already that I could use for these purposes. If there isn't I will definitely consider it.

PAPI placeholders as rankup requirements would be such a nieche use case though I think. The idea is certainly worth looking into but expect no results going in that direction. While I do plan on integrating PAPI and creating placeholders for the ranks, I don't know if PAPI will come to use in any capacity outside of that scope.

Again, thank you for your kind words and your suggestion!
