### ISSUE TITLE
Hi Blocky! Wondering if there was an ETA on BlockyRanks for 1.14?

### ISSUE THREAD

**Issue by MrWardy** [BlockyBorzan/BlockyRanks#2]
I love your plugin, I'm not kidding or exaggerating when I say it's one of the best I've seen. I saw your plugin on Spigot many months ago and instantly wrote that link down somewhere because I knew that I would need to have your plugin on my server, it's exactly what I was looking for and would set my server apart.

I know on Spigot in a review you said that BlockyRanks **will** be updated to 1.14.4, that unfortunately was back on May 15th, and you haven't been on Spigot in 3 weeks.

I'm just looking so I can plan ahead of my server since whether or not we can use BlockyRanks will affect a few bigger things.

**Comment by BlockyBorzan** [comment]
Hi!

Thank you for the praise. I really do plan on picking up developing plugins again in the near future, however my schedule is still packed as can be. Every time I think I have a little time to do some stuff for my spigot content, life throws me a curveball and I have to struggle to not get burned out. 

I hope I can release a version of BlockyRanks for 1.14 within the next two to four weeks as it seems that I will finally have some more free time on my hands by then. Closer to two than to four ;)

I hope your server will be just how you want it to be and I would love to get a link to it when it goes live so I can check it out some time! 

Best of Luck!

**Comment by MrWardy** [comment]
Great! Thank you so much of the kindness and update! I appreciate it and really hope all goes well. I'm very excited, and cannot wait to use your plugin. It has made it possible to add some very unique features with your branch system, as well as overall upgrade our past rank up system.

And for sure I will send you a link when it is released. I appreciate the encouragement.

**Comment by BlockyBorzan** [comment]
Hey, 

I thought I'd let you know a 1.14.4 version is done. It's not entirely tested yet but everything I have tested worked as expected.

Maybe try it out on your server if you feel like it :) 

Cheers!

**Comment by MrWardy** [comment]
Perfect! I appreciate the update, I've hit a wall in my schedule, but I'll add it and definitely start using it in the next few weeks.
