### ISSUE TITLE
BlockyRanks does not support 1.16.2

### ISSUE THREAD

**Issue by Fr0sto** [BlockyBorzan/BlockyRanks#7]
Hi. BR was working perfectly fine for me in 1.16.1, but upon updating to Paper 1.16.2 (release candidate dev builds found in their discord server), the plugin is completely disabled and throws this error on startup.

24.08 19:09:58 [Server] INFO [BlockyRanks] Enabling BlockyRanks v1.6.0
24.08 19:09:58 [Server] INFO [BlockyRanks] | Failed to load the Jobs plugin. It might be disabled or not present at all. Jobs related functionality is disabled.
24.08 19:09:58 [Server] ERROR [BlockyRanks] | Oops! Something went horribly wrong while enabling BlockyRanks. Disabling plugin.
24.08 19:09:58 [Server] INFO [BlockyRanks] | Disabled BlockyRanks                                        
24.08 19:09:58 [Server] WARN java.lang.NullPointerException
24.08 19:09:58 [Server] WARN at me.blocky.ranks.lib.nms.NMS.getDescriptorStringFromItem(NMS.java:56)
24.08 19:09:58 [Server] WARN at me.blocky.ranks.lib.item.ItemHelper.getItemDescriptor(ItemHelper.java:77)
24.08 19:09:58 [Server] WARN at me.blocky.ranks.config.branch.BranchConfigHandler.createBranch(BranchConfigHandler.java:189)
24.08 19:09:58 [Server] WARN at me.blocky.ranks.datastruct.WorldHandler.initialize(WorldHandler.java:133)
24.08 19:09:58 [Server] WARN at me.blocky.ranks.datastruct.WorldHandler.<init>(WorldHandler.java:89)
24.08 19:09:58 [Server] WARN at me.blocky.ranks.gui.GuiHandler.initialize(GuiHandler.java:149)
24.08 19:09:58 [Server] WARN at me.blocky.ranks.gui.GuiHandler.<init>(GuiHandler.java:128)
24.08 19:09:58 [Server] WARN at me.blocky.ranks.BlockyRanks.onEnable(BlockyRanks.java:236)
24.08 19:09:58 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
24.08 19:09:58 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
24.08 19:09:58 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
24.08 19:09:58 [Server] WARN at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499)
24.08 19:09:58 [Server] WARN at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413)
24.08 19:09:58 [Server] WARN at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
24.08 19:09:58 [Server] WARN at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241)
24.08 19:09:58 [Server] WARN at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
24.08 19:09:58 [Server] WARN at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
24.08 19:09:58 [Server] WARN at java.base/java.lang.Thread.run(Unknown Source)

**Comment by BlockyBorzan** [comment]
Fixed
