### ISSUE TITLE
[Suggestion] More customization for /ranks gui

### ISSUE THREAD

**Issue by MrWardy** [BlockyBorzan/BlockyRanks#8]
Hello! I'd just like to start off with how freaking much I love this plugin, I've never seen anything like it, with all the features, active development and clean easy to read and understand wiki and config comments.

My suggestion is in 2 parts,

The first being I think it would be great to add more customization for the item structure (similar to other sections of the gui.yml config) of /ranks because when I laid out my ranks I planned to have a specific structure (image attached below) and possibly some fill items around it.

The other suggestion is allowing to change the item for surpassed, current or upcoming ranks like you can with making them glow. This is because I like using glass panes and wanted to use black stained panes as upcoming ranks and green stained panes as surpassed and the current rank.

If any of these are already possible and I seemed to have just missed them in the config and wiki please feel free to correct me. Again I can't begin to express how much I love this plugin, keep up the amazing work! I hate to see great developers get burnt out and abandon their great plugins.

**Comment by MrWardy** [comment]
Also, this is unrelated to my suggestion, but how could I go about adding 3 rank paths (without a default rank)? I think this is already possible? I just can't figure it out. I want the player to at some point select their rank path from 3 available ones, possibly the first time they rankup or something like that. Maybe by making the default branch for a player based on a permission they have?

**Comment by BlockyBorzan** [comment]
Hey MrWardy, 

Thanks very much for the kind words!

Regarding the first suggestion, I am not sure what item structure you mean exactly. Did you forget to attach an image?

Your second suggestion sounds great! I will add it to the list, however I am currently working on a complete rehaul of the plugin that adds a ton of new features and config options. And a (hopefully) better ui. So it will be a while before any non-bugfix changes and features make it into the plugin. 

However as I am a student who is also fulltime employed and has some longer work-trips coming up, I cannot say when the BlockyRanks 2.0 update will be finished. Stay tuned for that sometime in the future :)


Regarding your second comment: 
In order to set up 3 ranks that branch off of one single rank, all you have to do is specify 3 child branches (with the 3 ranks you want being the first ranks in those branches) for the branch with the rank you want to split off of. I hope I understood your issue correctly there.

If you have any more questions or feature requests, please do let me know!

Cheers,

Blocky

**Comment by MrWardy** [comment]
Ah yes haha I did forget to attach the image, basically being able to move the items in whatever way you wish, because as far as I know you cannot add any filler items with /ranks and the only structure is them going down the first row then moving to the next row, whereas I would like to do something like this
![Screenshot 2020-09-14 191724](https://user-images.githubusercontent.com/27183976/93157509-395ffd80-f6bf-11ea-926c-2514d4a54bdd.jpg)

As for the rest, thank you very much, I can understand being a student and having current plans, I am ecstatic to see what BlockyRanks 2.0 will bring when that is released and I appreciate that even though you don't have the time right now, that you listened to, considered and added my suggestions to a future list of features.

**Comment by BlockyBorzan** [comment]
Could you elaborate further on your UI idea? if the red glass is a placeholder for ranks, are all those ranks part of the same branch? I'm not sure what I am looking at exactly, but I am very much open to ideas.

Cheers,
Blocky

**Comment by MrWardy** [comment]
The red glass is all the ranks in 1 branch. So being able to change where the items are in the gui just like you can in /rankup
`  gui:
    '1': ['1', '1', '1', '2', '2', '2', '3', '3', '3']
    '2': ['1', 'a', '1', '2', 'p', '2', '3', 'c', '3']
    '3': ['1', '1', '1', '2', '2', '2', '3', '3', '3']
    #'4': []
    #'5': []
    #'6': []`

**Comment by MrWardy** [comment]
> Regarding your second comment:
> In order to set up 3 ranks that branch off of one single rank, all you have to do is specify 3 child branches (with the 3 ranks you want being the first ranks in those branches) for the branch with the rank you want to split off of. I hope I understood your issue correctly there.
> 
> If you have any more questions or feature requests, please do let me know!
> 
> Cheers,
> 
> Blocky

Also, this isn't quite what I meant, I just now got to begin able to try and figure this out, which is why I comment on it now. I wish to have 1 different rank branching off into 3 different ranks so-to-speak. This way players can choose their rank "path" from the start of the game which may come with slightly different perks or features for each rank "path". These rank paths will contain many individual ranks inside of them which unlock new perks, some the same as their path counterpart, some different if that makes sense.

**Comment by MrWardy** [comment]
With this I want to be able to set multiple branches for one world

**Comment by BlockyBorzan** [comment]
Unfortunately this is not yet possible for the same world. There can only be one starting rank per world. 
What you can do though is have that starting rank be the only rank in its branch (So the starting branch has only 1 rank), and that rank can have your 3 desired child branches. Then just set up your permissions provider such that any new player automatically starts at the default rank. For them it would be as if they are choosing their path from the beginning with their first rankup. (almost)

**Comment by MrWardy** [comment]
What happens if you set multiple child branches when the player ranks up to the last rank in the parent branch? Does the player get to choose from one of the 3 branches, or do they get to rank up in all of the branches?

**Comment by MrWardy** [comment]
I just tried it with 1 branch proceeding into 3 different branches and all that seems to happen is it is selecting only one branch as the child? But oddly it is ignoring the first rank in that child branch.

**Comment by BlockyBorzan** [comment]
That is very unusual. I could not reproduce this issue. Could you send me your BlockyRanks folder so I can take a look?
